### PR TITLE
Add new OAuth2-based authentication strategy

### PR DESCRIPTION
**Pull request by timshadel**
We're asking all developers to move to [our new OAuth 2.0 authentication strategy](https://familysearch.org/developers/docs/oauth2). We're [actively discouraging](https://familysearch.org/developers/docs/authentication) the continued use of the old OAuth 1.0a approach, and as such we've made a very small, but API-breaking change to move that strategy out of the way and make it obvious that it is much less preferred.

The changes in usage are minor, and (except for the `profile` object changes) they are detailed in the README.md update. As these changes _are_ API-breaking, we have revved the major version number in keeping with [semver](http://semver.org/). We've added additional tests for this new `Strategy`, and renamed the previous files as needed to reflect they focus on the legacy API.

We've also lightened up the dependencies needed by taking the change proposed by Logan Allred in #1 to use the pure JSON API method, so if you pull this change you shouldn't need to pull the other. That change removes the need for `xml2js`.

Finally, we've also updated the `profile` object to use the new [FamilySearch Platform API](https://familysearch.org/developers/docs), and ensured that the data in the profile object matches what's available using that [new API](https://familysearch.org/platform/). Naturally, along with this change, we've added another fully-working example similar to the existing one.

### CODE REVIEW

**Comment by camshaft** [comment]
:+1:

**Comment by timshadel** [comment]
@jaredhanson Do you have any concerns with this approach, or things you'd ask us to change before pulling it in? We'd love to get it fixed up to your standards and get it pulled in and pushed to the npm registry as soon as reasonable. :-)

**Comment by jaredhanson** [comment]
Nope, this looks great.  I'm currently in-process of getting caught up on Passport-related pull requests.  It's my intent to get this merged by end-of-week.

**Comment by timshadel** [comment]
Fantastic. Thanks! :-) We're excited to make it a core part of our stack at FamilySearch.

**Comment by jaredhanson** [comment]
Cleanest pull request ever, thanks!  Merged and published to npm as passport-familysearch v1.0.0.  I've also given you commit rights to the repo; feel free to push changes directly.

One question: what's the usage on the `signer` option and its `signer.clientSecret()` function? https://github.com/jaredhanson/passport-familysearch/blob/master/lib/passport-familysearch/strategy.js#L75

Might be worth documenting if it is typically used.

Only changes are that I removed the `sessionKey` option (it's only relevant to OAuth 1.0), and I updated some metadata files to match the rest of my repos.

**Pull request merged**
